# All Permission
# This permissions can be selected for every Role or User

Administration:
  access_administration: Grant access to the administration Area
  set_permissions: Set Permissions for Roles
  administer_catalog: Administer the Catalogs
  view_status_report: View Status Report
  backup_recover: Backup and Recover Database

User:
  create_user: Create a User
  view_user: View all Users
  view_own_user: View own Users
  edit_user: Edit every User
  edit_own_user: Edit own User
  delete_user: Delete every User

Appointment:
  create_appointment: Create an Appointment
  view_appointment: View all Appointments
  edit_appointment: Edit every Appointment
  delete_appointment: Delete every Appointment

Domain:
  create_domain: Create a Domain
  view_domain: View all Domains
  edit_domain: Edit every Domain
  delete_domain: Delete every Domain

Task:
  create_task: Create a Task
  view_own_task: View own Tasks
  view_all_tasks: View all Tasks of every domain
  view_domain_task: View only own domain Tasks
  edit_task: Edit every Task
  edit_own_task: Edit own Task
  delete_task: Delete every Task
  delete_own_task: Delete own Task
  fill_every_task: Fill out every Task, independet of own domain
  fill_own_domain_task: Fill out only Tasks of own domain
  show_result_task: Show Results of every Task
  show_result_own_task: Show Results of own Task

Treatment:
  create_treatment: Create a Treatment
  view_treatment: View all Treatments
  edit_treatment: Edit every Treatment
  delete_treatment: Delete every Treatment

Patient:
  create_patient: Create a Patient
  view_patient: View all Patients
  edit_patient: Edit every Patients
  delete_patient: Delete every Patients

Medical Report:
  create_medical_report: Create Medical Report
  view_medical_report: View all Medical Reports
  edit_medical_report: Edit any Medical Report
  delete_medical_report: Delete any Medical Report

Report Header:
  create_reportheader: Create Report Header
  view_reportheader: View all Report Headers
  edit_reportheader: Edit all Report Headers
  delete_reportheader: Delete any Report Header
  set_default_reportheader: Set default Report Header

Medical Templates:
  create_medical_templates: Create Medical Templates
  view_medical_templates: View Medical Templates
  edit_medical_templates: Edit any Medical Template
  delete_medical_templates: Delete Medical Templates

Comment:
  create_comment: Create a Comment
  view_comment: View all Comments
  edit_comment: Edit every Comment
  delete_comment: Delete every Comment

Medication:
  create_medication: Create a Medication
  view_medication: View all Medications
  edit_medication: Edit every Medication
  delete_medication: Delete every Medication

Diagnosis:
  create_diagnosis: Create a Diagnosis
  view_diagnosis: View all Diagnosises
  edit_diagnosis: Edit every Diagnosis
  delete_diagnosis: Delete every Diagnosis

CaseFile:
  create_casefile: Create a CaseFile
  view_casefile: View all CaseFiles
  edit_casefile: Edit every CaseFile
  delete_casefile: Delete every CaseFile
  setactive_casefile: Activate old CaseFile for View

Anamnese:
  access_anamese: Access to Anamnese Data

Findings:
  access_finding: Access to Finding Data
